all_tables = [
    "Accessibility",
    "ActivityLog",
    "Address",
    "AlternateContact",
    "AmiChart",
    "Applicant",
    "ApplicationFlaggedSet",
    "ApplicationMethods",
    "Applications",
    "Assets",
    "CronJob",
    "Demographics",
    "GeneratedListingTranslations",
    "HouseholdMember",
    "Jurisdictions",
    "ListingEvents",
    "ListingFeatures",
    "ListingImages",
    "ListingMultiselectQuestions",
    "ListingNeighborhoodAmenities",
    "ListingUtilities",
    "Listings",
    "MapLayers",
    "Migrations",
    "MultiselectQuestions",
    "PaperApplications",
    "ReservedCommunityTypes",
    "Translations",
    "UnitAccessibilityPriorityTypes",
    "UnitAmiChartOverrides",
    "UnitGroup",
    "UnitGroupAmiLevels",
    "UnitRentTypes",
    "UnitTypes",
    "Units",
    "UnitsSummary",
    "UserPreferences",
    "UserAccounts",
    "UserRoles",
]

public_tables = [
    "accessibility",
    "address",
    "alternate_contact",
    # "ami_chart", 
    "applicant",
    "application_flagged_set",
    "application_methods",
    "applications",
    "assets",
    "demographics",
    "household_member",
    "jurisdictions",
    "listing_events",
    "listing_images",
    "listing_multiselect_questions"
    "listings",
    "multiselect_questions",
    "paper_applications", 
    "reserved_community_types",
    "unit_accessibility_priority_types",
    "unit_ami_chart_overrides",
    "unit_rent_types",
    "unit_types",
    "units",
    "units_summary",
    "user_accounts",
    "user_roles",
]

pii_tables = [
    "address",
    "alternate_contact",
    "applicant",
    "application_flagged_set"
    "applications",
    "household_member",
    "user_accounts",
]

non_pii_tables = [
    "accessibility",
    "application_methods",
    "assets",
    "demographics",
    "jurisdictions",
    "listing_events",
    "listing_images"
    "listing_multiselect_questions",
    "listings",
    "multiselect_questions",
    "paper_applications",
    "units",
    "user_roles"
]

type_tables = [
    "reserved_community_types",
    "unit_accessibility_types",
    "unit_rent_types",
    "unit_types",
]